services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: doctofree
      MARIADB_USER: doctofree_user
      MARIADB_PASSWORD: doctofree_pwd
    volumes:
      - doctofree_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  doctofree_db_data:
